// This file was automatically generated by braintrust pull. You can
// generate it again by running:
//  $ braintrust pull --project-name "Unreleased"
// Feel free to edit this file manually, but once you do, you should make sure to
// sync your changes with Braintrust by running:
//  $ braintrust push "braintrust/unreleased.ts"

import braintrust from "braintrust";

const project = braintrust.projects.create({
  name: "Unreleased-AI",
});

export const generateChangelog1 = project.prompts.create({
  name: "Generate changelog 1",
  slug: "generate-changelog-1",
  description: "Generate a changelog from a list of unreleased commits",
  model: "gpt-4o",
  messages: [
    {
      content:
        "Summarize the following commits from {{url}} since {{since}} in changelog form. Include a summary of changes at the top since the provided date, followed by individual pull requests (be concise).\n" +
        "\n" +
        "{{commits}}",
      role: "user",
    },
  ],
});

export const generateChangelog2 = project.prompts.create({
  name: "Generate changelog 2",
  slug: "generate-changelog-2",
  description: "Generate a changelog from a list of unreleased commits",
  model: "gpt-4o",
  messages: [
    {
      content:
        "Create a developer-focused changelog from the commits below, covering changes from {{url}} since {{since}}.\n" +
        "\n" +
        "**Output Format:**\n" +
        "1. Executive Summary (2-3 sentences highlighting the most significant changes)\n" +
        "2. Categorized Changes:\n" +
        "   - 🚨 Breaking Changes\n" +
        "   - ✨ New Features\n" +
        "   - 🔧 Improvements\n" +
        "   - 🐛 Bug Fixes\n" +
        "\n" +
        "**Guidelines:**\n" +
        "- Use bullet points with concise descriptions\n" +
        "- Include PR numbers in parentheses when available\n" +
        "- Prioritize user-facing and API changes\n" +
        "- Skip routine maintenance, dependency updates, and merge commits\n" +
        "- Highlight security-related changes\n" +
        "\n" +
        "**Source Data:**\n" +
        "{{commits}}",

      role: "user",
    },
  ],
});
